### ISSUE TITLE
Worker remote control

### ISSUE THREAD

**Issue by hchienjo** [avkhozov/Minion-Backend-Mango#1]
Starting a worker process immediately fails with the error `Worker error: Method "receive" not implemented by subclass`

There is no method `receive` in the Mango.pm file.

**Comment by restump** [comment]
I found this as well.  Looks like Minion was bumped to version 6, which added the receive method to the base class implementation.  The Mango backend hasn't been updated, but was targeting Minion version 5?

**Comment by avkhozov** [comment]
For now `Minion::Backend::Mango` doesn't compatible with a new `Minion` (6.0+). I've released version 1.01 which works with new `Minion` (worker will not fall with the error), but worker remote control still doesn't work.

**Comment by hchienjo** [comment]
Is there any way I can help? I looked at the original Pg backend [implementation](https://github.com/kraih/minion/blob/master/lib/Minion/Backend/Pg.pm#L96) and the `receive` and I am really interested in helping out if that is okay with you.

**Comment by avkhozov** [comment]
Feel free to create a pull request for this feature, I'll be happy!

We need create a new field `inbox` in workers collection and implement `broadcast` and `receive` methods. Also don't forget about test, see example [here](https://github.com/kraih/minion/blob/master/t/pg.t#L657-L684).

**Comment by avkhozov** [comment]
Added in 9c3dca1c3cb85a4f7693383f15e2ada09fd31fe5.
