### ISSUE TITLE
Not compatible with the latest version of Minion

### ISSUE THREAD

**Issue by marghidanu** [avkhozov/Minion-Backend-Mango#4]
When using it with the latest version of Minion the Minon admin interface from Mojolicious gives back some errors:

`Not a HASH reference at /usr/local/share/perl5/Mojolicious/Plugin/Minion/Admin.pm line 59.`

I believe the interface for Minon::Backend has changed since 2017 and maybe the package needs to be update.

**Comment by avkhozov** [comment]
The module is now abandoned, I recomend to use https://github.com/avkhozov/Minion-Backend-MongoDB module (although `MongoDB` perl module also stopped updating... https://github.com/mongodb/mongo-perl-driver). But PR are welcome.
